### ISSUE TITLE
CodeMirror/Android editor: Long press on a single word doesn't open the context menu.

### ISSUE THREAD

**Issue by personalizedrefrigerator** [personalizedrefrigerator/joplin#1]
This might be because drawSelection is enabled.

## Environment

Platform: Android (doesn't happen on iOS)
OS specifics: Android 12/Samsung OneUI (doesn't happen on Android emulator)

## Steps to reproduce

1. Enable the beta editor
2. Open a note
3. Long-press on a word

**Comment by laurent22** [comment]
I guess this bug should be open on the main repo now that the feature is merged in. Is there any solution to this? What is drawSelection, is that the feature that highlight similar words? In which case I think that could be disabled for now as that's a lot less important than working copy and paste.

**Comment by personalizedrefrigerator** [comment]
`drawSelection` has CodeMirror draw the selected regions instead of the browser.

On my tablet, tripple-tap doesn't select text in other text inputs. CodeMirror, however, seems to have a custom gesture mapping tripple-tap to selection. When CodeMirror changes the selection, the WebView seems not to recognize that the selection change was initiated by the user (and thus that an edit menu should be visible).


> In which case I think that could be disabled for now as that's a lot less important than working copy and paste.

A long-press on the word still displays the copy/paste menu (on my tablet).

**Comment by laurent22** [comment]
I'm not sure about the technical details but since this is a native feature it's important that it is well supported. For me it's mostly broken on my phone (Samsung Galaxy S9):

- Long press almost works but is buggy - the menu briefly appears then disappear immediately.

- Double tap, which should also display menu (it does in standard text fields like the title field) only selects the text but doesn't display the menu.

- Triple tap selects the current paragraph, but doesn't display the context menu (it should)

**Comment by personalizedrefrigerator** [comment]
I'm able to reproduce this with no CodeMirror extensions and in the editor on `codemirror.net`. I'm reporting it as a bug upstream.

Note that removing the `mousedown` listener in the Chrome developer tools seems to fix the issue.
![](https://user-images.githubusercontent.com/46334387/188138564-204c7e21-0cd5-433f-b966-f5af9959adbb.png)
It probably causes other issues, however!

**Comment by personalizedrefrigerator** [comment]
Upstream bug: https://github.com/codemirror/dev/issues/935

**Comment by personalizedrefrigerator** [comment]
Moving this issue to the main repository.
